services:
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER:-yourusername}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-yourpassword}
      - POSTGRES_DB=${DB_NAME:-yourdbname}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-yourusername} -d ${DB_NAME:-yourdbname}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    volumes:
      - .:/app:cached
    ports:
      - "80:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-yourusername}:${DB_PASSWORD:-yourpassword}@db:5432/${DB_NAME:-yourdbname}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    env_file:
      - ./.env
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
