"""change_ips_from_int_to_str

Revision ID: 9d34177f9909
Revises: bc03b9831e8c
Create Date: 2024-11-23 20:10:43.221963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d34177f9909'
down_revision: Union[str, None] = 'bc03b9831e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ip_lists', 'ip_address',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('mouse_events', 'ip_address',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('network_events', 'ip_address',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('text_messages', 'ip_address',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('text_messages', 'ip_address',
               existing_type=sa.String(length=255),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('network_events', 'ip_address',
               existing_type=sa.String(length=255),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('mouse_events', 'ip_address',
               existing_type=sa.String(length=255),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('ip_lists', 'ip_address',
               existing_type=sa.String(length=255),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
