"""Initial migration

Revision ID: 737a3096074f
Revises: 
Create Date: 2024-11-23 15:39:36.279546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '737a3096074f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_ips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.BigInteger(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('blocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address')
    )
    op.create_index(op.f('ix_blocked_ips_id'), 'blocked_ips', ['id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.BigInteger(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('mouse_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.BigInteger(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('viewport_x', sa.Integer(), nullable=False),
    sa.Column('viewport_y', sa.Integer(), nullable=False),
    sa.Column('is_malicious', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mouse_events_id'), 'mouse_events', ['id'], unique=False)
    op.create_table('network_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.BigInteger(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=False),
    sa.Column('method', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('is_malicious', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_events_id'), 'network_events', ['id'], unique=False)
    op.add_column('text_messages', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.add_column('text_messages', sa.Column('ip_address', sa.BigInteger(), nullable=False))
    op.add_column('text_messages', sa.Column('type', sa.String(length=255), nullable=False))
    op.add_column('text_messages', sa.Column('is_malicious', sa.Boolean(), nullable=True))
    op.add_column('text_messages', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('text_messages', 'message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'text_messages', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'text_messages', type_='foreignkey')
    op.alter_column('text_messages', 'message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('text_messages', 'updated_at')
    op.drop_column('text_messages', 'is_malicious')
    op.drop_column('text_messages', 'type')
    op.drop_column('text_messages', 'ip_address')
    op.drop_column('text_messages', 'customer_id')
    op.drop_index(op.f('ix_network_events_id'), table_name='network_events')
    op.drop_table('network_events')
    op.drop_index(op.f('ix_mouse_events_id'), table_name='mouse_events')
    op.drop_table('mouse_events')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_blocked_ips_id'), table_name='blocked_ips')
    op.drop_table('blocked_ips')
    # ### end Alembic commands ###
