"""add_caused_block_to_text_message

Revision ID: bc03b9831e8c
Revises: 296c754dec63
Create Date: 2024-11-23 20:07:30.341759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc03b9831e8c'
down_revision: Union[str, None] = '296c754dec63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text_messages', sa.Column('caused_block', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text_messages', 'caused_block')
    # ### end Alembic commands ###
