name: Deployment Workflow
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ssh connection
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/anomala/backend
          docker compose down
          git pull
          docker compose build
          docker compose up -d
